const actionConstants = {
  COMPLETE: 'COMPLETE',
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_FIRSTNAME: 'UPDATE_FIRSTNAME',
  UPDATE_LASTNAME: 'UPDATE_LASTNAME',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  UPDATE_COUNTRY_CODE: 'UPDATE_COUNTRY_CODE',
  UPDATE_PHONE_NUMBER: 'UPDATE_PHONE_NUMBER',
  UPDATE_TERMSANDCONDITION: 'UPDATE_TERMSANDCONDITION',
};

export default actionConstants;
